repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests for backend
        entry: python3 -m unittest discover -s ./tests -p "*.py"
        language: system
        pass_filenames: false
        always_run: true

      - id: format-check
        name: Check format for backend
        entry: black --check --diff src
        language: system
        pass_filenames: false
        always_run: true

      - id: black
        name: Format code for backend
        entry: black src
        language: system
        pass_filenames: false
        always_run: true