services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://app_user:app_password@db:5433/app_db
    depends_on:
      - db
    volumes:
      - ./src:/usr/local/app/src
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Directorio local
    ports:
      - "5433:5432"
    restart: unless-stopped
