services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - ./src:/usr/local/app/src
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Directorio local
    ports:
      - "5433:5432"
    restart: unless-stopped
