name: Test backend
on:
  push:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -s src/tests -p "*.py"
  
  format-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black  # Ensure black is installed
      - name: Run Black
        run: |
          black --check --diff .